dependencies:
- name: spring-boot-ab
  version: 0.1.0
  repository: https://artifactory-tools.dte-ocp46-rm0ee6-915b3b336cabec458a7c7ec2aa7c625f-0000.us-east.containers.appdomain.cloud/artifactory/generic-local/dev-ab/
